
### 创建一个规则：数字条件
POST http://localhost:8080/rule
Content-Type: application/json

{
  "name": "规则2",
  "desc": "第一个规则",
  "condition": "c == 3"
}

### 使用规则
GET http://localhost:8080/rule/规则2?c=1

### 创建一个规则：布尔条件
POST http://localhost:8080/rule
Content-Type: application/json

{
  "name": "规则3",
  "desc": "第一个规则",
  "condition": "c == true"
}

### 使用规则
GET http://localhost:8080/rule/规则3?c=true


### 创建一个规则：字符串
POST http://localhost:8080/rule
Content-Type: application/json

{
  "name": "规则3",
  "desc": "第一个规则",
  "condition": "c == '某某某'"
}

### 使用规则
GET http://localhost:8080/rule/规则3?c=某某某

### 创建一个规则：实际业务场景
POST http://localhost:8080/rule
Content-Type: application/json

{
  "name": "政策业务规则",
  "desc": "订单中可下政策的限制规则",
  "condition": "department =~ ['1','2','3','4'] and workAge >= 0 and workAge <= 10  and customerLevel =~ ['39','40','41','42','43','44'] "
}

###
POST http://localhost:8080/rule
Content-Type: application/json

{
  "name": "政策业务规则",
  "desc": "订单中可下政策的限制规则",
  "condition": "a == 1 and (b >= 2 or c <= 10)"
}
