### 使用数字规则
GET {{prefix}}{{ip}}:{{port}}/rule/数字规则1?c=3


### 使用布尔规则
GET {{prefix}}{{ip}}:{{port}}/rule/布尔规则2?c=true


### 使用字符规则
GET {{prefix}}{{ip}}:{{port}}/rule/字符规则3?c=某某某


### 使用自定义规则
GET {{prefix}}{{ip}}:{{port}}/rule/自定义规则4?c=39

### 使用自定义规则
GET {{prefix}}{{ip}}:{{port}}/rule/自定义规则5?c=abs

# todo 使用get请求以及map来接收通用的参数（数字、字符串、集合等类型）
### 使用集合规则
GET {{prefix}}{{ip}}:{{port}}/rule/规则3?c=1,2

### 使用集合规则
GET {{prefix}}{{ip}}:{{port}}/rule/规则3?a=1.1&c=1&c=2&b=1&d=1298719&e=周强&f=true&g=&h=null


### 使用集合规则
GET {{prefix}}{{ip}}:{{port}}/rule?facts=%0A%7B%0A%22c%22:%5B1,2%5D%0A%7D%0A

### 使用集合规则
#  { "a": 1, "b": "2", "c": 2.333, "d": [ 1, 2, 3 ], "e": [ "1", "2,", "4" ], "f": true }
GET {{prefix}}{{ip}}:{{port}}/rule?
    facts=%7B%0A%20%20%22a%22%3A%201%2C%0A%20%20%22b%22%3A%20%222%22%2C%0A%20%20%22c%22%3A%202.333%2C%0A%20%20%22d%22%3A%20%5B%0A%20%20%20%201%2C%0A%20%20%20%202%2C%0A%20%20%20%203%0A%20%20%5D%2C%0A%20%20%22e%22%3A%20%5B%0A%20%20%20%20%221%22%2C%0A%20%20%20%20%222%2C%22%2C%0A%20%20%20%20%224%22%0A%20%20%5D%2C%0A%20%20%22f%22%3A%20true%0A%7D
